[package]
    edition="2024"
    name="rusty-blox"
    version="0.1.0"

[dependencies]
    libloading="0.9.0"
roblox-runtime={path="roblox-runtime"}
gtk4 = "0.10"
libc = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json="1.0.151"
ureq="3.3.0"
winit="0.30.13"
wayland-backend = { version = "0.3.17", features = ["client_system"] }
wayland-client = "0.31.15"
zbus = { version = "5.18.0", features = ["blocking"] }
zstd="0.13"
zip={version="8.6.0", default-features=false, features=["deflate"]}
